name: Lint Code
description: A custom action for linting JavaScript code
inputs:
  target:
    description: "The directory or files to lint"
    required: true
outputs:
  lint-result:
    description: "The result of the linting process"
runs:
  using: "node16"
  main: "index.js"
