name: Hands-on-Assignment-3

on:
  push:
    branches:
      - main
      - lesson3

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run style check
        uses: ./.github/actions/check-style
        with:
          directory: "assignment"
        continue-on-error: true
  
  tests:
    runs-on: ubuntu-latest
    needs: style-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r assignment/requirements.txt

      - name: Run test
        run: pytest --verbose
