name: Hands-on-Assignment-3

on:
  push:
    branches:
      - main
      - lesson3

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: npm install

      - name: Run custom action
        uses: ./.github/actions/lint
        with:
          target: "src/*.js"

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: npm install

      - name: Run test
        run: npm test
