name: Hands-on-Assignment-3

on:
  push:
    branches:
      - main
      - lesson3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install custom action deps
        uses: npm install
        working-directory: .github/actions/lint

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run custom lint action
        uses: ./github/actions/lint
        with:
          target: "src/*.js"
